version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_TYPE=postgresql
      - POSTGRES_URL=postgresql://fileshare:password@db:5432/fileshare
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./certs:/app/certs
    depends_on:
      - db
    networks:
      - fileshare-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=fileshare
      - POSTGRES_USER=fileshare
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fileshare-network

volumes:
  postgres_data:

networks:
  fileshare-network:
    driver: bridge